### PR TITLE
Add MSON generator

### PR DESCRIPTION
**Pull request by mifkamaz**
Utility to create MSON on the base JSON

### CODE REVIEW

**Comment by kylef** [comment]
HI @mifkamaz,

I'm not able to get this website to work. Am I doing something wrong? Here's a quick gif of what I'm seeing:



When I enter JSON and hit "Parse" it loads a white screen.

**Comment by mifkamaz** [comment]
Hi. 
Its work correctly.
For generate you must be add root key to JSON, he use for object naming.

**Comment by mifkamaz** [comment]
Hey @kylef.
Please check again your JSON

```
{
    "name": "style"
}
```

**Comment by kylef** [comment]
@mifkamaz Ah, that works now. There are some other cases that don't seem to work correctly (arrays). I think it would be great to add some documentation on what is supported on the page or perhaps an example. There is just a textarea when you open the page and for newcomers it may be confusing what the expected input format is.

```apib
[
  {
    "name: "kyle"
  }
]
```

**Comment by mifkamaz** [comment]
@kylef 
I fix error parse arrays & add little description to page.
Any other suggestions?

**Comment by kylef** [comment]
@mifkamaz Thanks, that's much clearer now. Great job on this tool.

**Comment by nikvdp** [comment]
@mifkamaz is the source for this still available? The repository at https://github.com/mifkamaz/mson_generator_w seems to have been deleted

**Pull request merged**
