### PR TITLE
Activates current page in the docs navigation

### PR DESCRIPTION
**Pull request by w-vi**
Crude attempt to fix the docs navigation to highlight the current page.

### CODE REVIEW

**Comment by w-vi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GvFtZ6Sf&#x2F;392-change-navigation-for-the-documentation-section-of-apiblueprint-org-to-refract-the-current-page-in-navigation-ui"> Change navigation for the documentation section of apiblueprint.org to refract the current page in navigation UI</a>

**Comment by pksunkara** [comment]
We are using bootstrap.js, so let's use that instead of this method. https://github.com/apiaryio/apiblueprint.org/blob/f37b1b60f535dc8c0775966618c031a7645b4f16/source/layouts/layout.erb#L114

**Comment by w-vi** [comment]
If we want the JS approach please close this and implement it. It would take me too much time to learn it, I have barely any experience with the bootstrap.js and browser JS in general. 

I actually never liked it, as it renders the pages less useful when JS is not available.

**Comment by kylef** [comment]
I think I'd prefer it if this didn't require JS if we can, however checking the titles is a little fragile.

What about using the sitemap in middleman to completely generate the menu?

You can find a short example at https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/traversal-app/source/layout.erb and more documentation on sitemaps: https://middlemanapp.com/advanced/sitemap

This way, we no longer have to manually construct this menu, and instead it shows all pages within the documentation section.

**Comment by w-vi** [comment]
I didn't know about the middleman, that looks promising and sure a bit more robust that title checking.

**Comment by w-vi** [comment]
@kylef updated

**Pull request merged**
